//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentsDetail
    {
        public int InstrumentDetailID { get; set; }
        public int InstrucmentID { get; set; }
        public string HouryThreshold { get; set; }
        public string FourHourThreshold { get; set; }
        public string DailyThreshold { get; set; }
        public string HourlyThresholdPercent { get; set; }
        public string FourHourThresholdPercent { get; set; }
        public string DailyThresholdPercent { get; set; }
    }
}
