//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketData
    {
        public int MarketDataID { get; set; }
        public int MarketID { get; set; }
        public int ExchangeID { get; set; }
        public int InstrumentID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public decimal OpenPrice { get; set; }
        public decimal ClosePrice { get; set; }
        public decimal HighPrice { get; set; }
        public decimal LowPrice { get; set; }
    
        public virtual Exchanges Exchanges { get; set; }
        public virtual Instruments Instruments { get; set; }
        public virtual Markets Markets { get; set; }
    }
}
