//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketsEntities : DbContext
    {
        public MarketsEntities()
            : base("name=MarketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrentAggData> CurrentAggData { get; set; }
        public virtual DbSet<CurrentData> CurrentData { get; set; }
        public virtual DbSet<Exchanges> Exchanges { get; set; }
        public virtual DbSet<Instruments> Instruments { get; set; }
        public virtual DbSet<MarketData> MarketData { get; set; }
        public virtual DbSet<Markets> Markets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<InstrumentsDetail> InstrumentsDetail { get; set; }
    }
}
